version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:20"
    groups:
      android-gradle:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:40"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
