package com.foxhole.beta.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

internal object TrafficMapTokens {
    val DashboardCardTotalHeight = 216.dp
    val DefaultCountryFill = Color(0xFF3E3F41)
    val DefaultCountryBoundary = Color(0xFF5B5D61)
    val LightRouteLine = Color(0xFFFAFAFA)
    val TorExit = Color(0xFFFF8A3D)

    const val DarkLandBaseAlpha = 0.46f
    const val LightLandBaseAlpha = 0.58f
    const val DarkLandDetailAlpha = 0.22f
    const val LightLandDetailAlpha = 0.30f
    const val DarkCountryBoundaryAlpha = 0.18f
    const val LightCountryBoundaryAlpha = 0.24f
    const val DarkOriginHighlightAlpha = 0.36f
    const val LightOriginHighlightAlpha = 0.30f
    const val DarkRouteLineAlpha = 0.88f
    const val DarkDestinationAlpha = 0.78f
    const val LightDestinationAlpha = 0.70f
    const val DarkPhoneScreenAlpha = 0.92f
    const val LightPhoneScreenAlpha = 0.94f
    const val DarkLegendTextAlpha = 0.88f
    const val LightLegendTextAlpha = 0.92f
    const val DarkInactiveTextAlpha = 0.72f
    const val LightInactiveTextAlpha = 0.76f
    const val OriginHighlightAlphaBase = 0.18f
    const val OriginHighlightAlphaRange = 0.16f
    const val DestinationHighlightAlphaBase = 0.18f
    const val DestinationHighlightAlphaRange = 0.30f
    const val RouteCountryHighlightAlphaBase = 0.32f
    const val RouteCountryHighlightAlphaRange = 0.23f
    const val CountryHighlightMinAlpha = 0.12f
    const val CountryHighlightMaxAlpha = 0.56f
    const val NewCountryStrokeAlpha = 0.78f
    const val ExistingCountryStrokeAlpha = 0.62f

    const val DashboardSectionGapDp = 6f
    const val HeaderOriginMinWidthDp = 136f
    const val HeaderOriginMaxWidthDp = 184f
    const val HeaderOriginIconDp = 13f
    const val HeaderOriginLabelFontSp = 9f
    const val HeaderOriginLabelLineSp = 10f
    const val HeaderOriginSkeletonGapDp = 3f
    const val HeaderOriginSkeletonPrimaryWidthDp = 86f
    const val HeaderOriginSkeletonSecondaryWidthDp = 62f
    const val HeaderOriginSkeletonHeightDp = 8f
    const val HeaderIconContainerAlpha = 0.56f
    const val HeaderIconPaddingDp = 5f
    const val HeaderIconSizeDp = 16f
    const val HeaderDetailsButtonSizeDp = 28f

    const val LoadingTopPaddingDp = 12f
    const val LoadingGapDp = 8f
    const val LoadingMapWidthFraction = 0.92f
    const val LoadingMapHeightDp = 86f
    const val LoadingMetricsWidthFraction = 0.72f
    const val LoadingMetricGapDp = 6f
    const val LoadingMetricPrimaryWidthDp = 42f
    const val LoadingMetricSecondaryWidthDp = 72f
    const val LoadingMetricHeightDp = 8f
    const val ShapeErrorPaddingHorizontalDp = 8f
    const val ShapeErrorPaddingVerticalDp = 10f
    const val ShapeErrorGapDp = 4f
    const val ShapeErrorTitleFontSp = 10f
    const val ShapeErrorTitleLineSp = 12f
    const val ShapeErrorHelperFontSp = 9f
    const val ShapeErrorHelperLineSp = 11f

    const val RouteMinStrokeDp = 0.9f
    const val RouteMaxStrokeDp = 2.2f
    const val MarkerCollisionDistancePx = 11f
    const val MarkerCollisionSweepDegrees = 137.5f
    const val MarkerCollisionMaxAttempts = 18
    const val MarkerCollisionRingSize = 6f
    const val MarkerRawMatchTolerancePx = 0.5f
    const val ExpandedRouteMinStrokeDp = 1.2f
    const val ExpandedRouteMaxStrokeDp = 3.1f
    const val RouteMinAlpha = 0.42f
    const val RouteAlphaRange = 0.36f
    const val RouteHaloStrokeExtraDp = 1.4f
    const val RouteHaloAlphaMultiplier = 0.22f
    const val RouteDirectionMinDistancePx = 18f
    const val RouteDirectionCueT = 0.66f
    const val RouteDirectionCueHaloAlpha = 0.62f
    const val TorRouteDashDp = 7f
    const val TorRouteGapDp = 4f
    const val RouteDirectionArrowSizeDp = 5.4f
    const val DetailRouteDirectionArrowSizeDp = 6.4f
    const val RoutePulseStartT = 0.22f
    const val RoutePulseEndT = 0.84f
    const val RoutePulseStrokeDp = 1.1f
    const val RoutePulseRadiusDp = 2.1f
    const val RoutePulseAlpha = 0.72f
    const val RoutePulseHaloAlpha = 0.58f
    const val DestinationRadiusDp = 3.15f
    const val EuropeDestinationRadiusDp = 2.35f
    const val RouteNodeRadiusDp = 2.75f
    const val TorNodeRadiusDp = 2.65f
    const val OriginPhoneWidthDp = 8.5f
    const val OriginPhoneHeightDp = 12.8f
    const val OriginPhoneCornerDp = 2.4f
    const val OriginPhoneScreenInsetDp = 1.4f
    const val OriginPhoneHomeRadiusDp = 0.65f
    const val MarkerClusterBadgeSizeDp = 17f
    const val MarkerClusterBadgeLiftDp = 14f
    const val MarkerClusterBadgeShiftDp = 6f
    const val MarkerClusterBadgeElevationDp = 1f
    const val MarkerClusterTextFontSp = 8f
    const val MarkerClusterTextLineSp = 8f
    const val MarkerTouchTargetDp = 44f
    const val MarkerCalloutWidthDp = 132f
    const val MarkerCalloutMinWidthDp = 96f
    const val MarkerCalloutHorizontalGapDp = 8f
    const val MarkerCalloutVerticalLiftDp = 40f
    const val MarkerCalloutSurfaceAlpha = 0.96f
    const val MarkerCalloutElevationDp = 2f
    const val MarkerCalloutPaddingHorizontalDp = 8f
    const val MarkerCalloutPaddingVerticalDp = 6f
    const val MarkerCalloutGapDp = 2f
    const val MarkerCalloutDetailFontSp = 10f
    const val MarkerCalloutDetailLineSp = 12f
    const val SmallCountryCalloutHaloAlpha = 0.78f
    const val SmallCountryCalloutStrokeAlpha = 0.92f
    const val SmallCountryCalloutMaxAreaPx = 46f
    const val SmallCountryCalloutRadiusDp = 4.5f
    const val SmallCountryCalloutStrokeDp = 1.2f
}
