build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

processors:
  active: true

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false

complexity:
  LongMethod:
    active: true
    threshold: 120
  LongParameterList:
    active: true
    functionThreshold: 16
    constructorThreshold: 16
  TooManyFunctions:
    active: true
    thresholdInFiles: 40

formatting:
  active: true
  android: true
  autoCorrect: false
  MaximumLineLength:
    active: false
